baseURL = "http://gradschooladvice.github.io"
languageCode = "en-us"
title = "Advice with Replacement"
theme = "cactus"

[submodule "public"]
    url = "https://github.com/gradschooladvice/gradschooladvice.github.io.git"
